/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.VitalSignHistory;
import model.VitalSigns;

/**
 *
 * @author zhengzhang
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    VitalSignHistory history;
    
    public CreateJPanel(VitalSignHistory history) {
        initComponents();
       this.history=history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Vital Signs");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 27, 272, 41));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Temperature:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 143, 121, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Blood Pressure:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 204, 121, 40));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Pulse:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 263, 121, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Date:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 316, 121, 40));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 205, 179, 40));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 264, 179, 40));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 317, 179, 40));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 152, 179, 40));

        btnSave.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 407, 133, 39));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

double temperature =Double.parseDouble(jTextField4.getText());
double pressure=Double.parseDouble(jTextField1.getText());
int pulse = Integer.parseInt(jTextField2.getText());
String date =jTextField3.getText();

VitalSigns vs = history.addNewVital();
vs.setTemperature(temperature);
vs.setPulse(pulse);
vs.setBloodPressure(pressure);
vs.setDate(date);

JOptionPane.showMessageDialog(this,"New Vital Signs Added");

jTextField4.setText("");
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");



    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
